-- Run this once in the Supabase SQL editor (project fmejfxejsrmjvexfizgj)
-- Creates separate tables for "מעוף מכירות" so its data never mixes with FreeFit's.

create table if not exists maof_agents (
  id bigint generated by default as identity primary key,
  name text not null
);

create table if not exists maof_daily_stats (
  id bigint generated by default as identity primary key,
  date date not null,
  agent_name text not null,
  calls integer default 0,
  hours numeric default 0,
  leads integer default 0,
  renewals integer default 0,
  hmo integer default 0,
  total_sales integer default 0,
  daily_leads integer default 0
);

-- Matches the existing agents/daily_stats tables: RLS off, anon key does all CRUD.
alter table maof_agents disable row level security;
alter table maof_daily_stats disable row level security;
